---
- name: Import a key for poastgres 10
  ansible.builtin.rpm_key:
    state: present
    key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-10


- name: Import a key poastgres 11
  ansible.builtin.rpm_key:
    state: present
    key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-11


- name: Import a key from a url 12
  ansible.builtin.rpm_key:
    state: present
    key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-12


- name: Import a key poastgres 13
  ansible.builtin.rpm_key:
    state: present
    key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-13


- name: Import a key for poastgres 14
  ansible.builtin.rpm_key:
    state: present
    key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-14

- name: postgres | setup dnf repository
  become: true
  ansible.builtin.dnf:
    update_cache: truefor postgresql"
    name:
      https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: postgres | install client packages
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name: >-
      postgresql{{ postgresql_version }}{{
        (postgresql_package_version | length > 0) |
        ternary('-' + postgresql_package_version, '')
      }}
    state: present
