---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: postgresql_exact
    image: centos:7
    groups:
      - exactversion
  - name: postgresql10
    image: centos:7
  - name: postgresql11
    image: centos:7
  - name: postgresql12
    image: centos:7
  - name: postgresql13
    image: centos:7
  - name: postgresql14
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      postgresql_exact:
        postgresql_version: "12"
        postgresql_package_version: "12.11"
      postgresql10:
        postgresql_version: "10"
      postgresql11:
        postgresql_version: "11"
      postgresql12:
        postgresql_version: "12"
      postgresql13:
        postgresql_version: "13"
      postgresql14:
        postgresql_version: "14"
  playbooks:
    converge: ../resources/playbook.yml
scenario:
  name: centos7
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
